### ISSUE TITLE
panic: interface conversion:

### ISSUE THREAD

**Issue by dtulyakov** [Evedel/bow#1]
запускаю скрипт ~/scripts/docker/Bowship/0run.sh

> docker pull evedel/bow;
> docker rm -vf Bowship;
> docker run -d \
>    --name=Bowship \
>    -e BS_LOG_SILENT=yes \
>    -v /home/root/db/bow:/var/lib/bow \
>    -p 5001:19808 \
>    evedel/bow;

контейнер сразу крашится 
`docker logs --tail=100 Bowship` выдаёт вот это

> [ Tue, 04 Oct 2016 04:53:19 UTC ][ L2 ] Server listening at [:19808]
> [ Tue, 04 Oct 2016 04:53:19 UTC ][ L2 ] DaemonManager: Sleep time is : 300 seconds
> panic: interface conversion: interface is nil, not []interface {}
> 
> goroutine 7 [running]:
> panic(0x8012a0, 0xc820048e00)
>   /usr/lib/go-1.6/src/runtime/panic.go:481 +0x3e6
> checker.CheckTags()
>   /app/src/checker/checker.go:96 +0x667
> created by checker.DaemonManager
>   /app/src/checker/checker.go:21 +0x1a4

подскажи куда копать?

**Comment by Evedel** [comment]
@dtulyakov, для начала, попробуй поменять
`-e BS_LOG_SILENT=yes \`
на 
`-e BS_LOG_SILENT=no \`
и посмотреть/показать что там в логах будет

**Comment by dtulyakov** [comment]
да всё то же
[paste.ofcode.org/Dd5DXKiR5MpYb8idKmc5bj](http://paste.ofcode.org/Dd5DXKiR5MpYb8idKmc5bj)

**Comment by Evedel** [comment]
@dtulyakov,  скорее всего, вы удаляли старые образы из репозитория с помощью апи регистри, в этом случае, в оперативной памяти регистри все еще остаются данные о нем. После перезагрузки регистри или запуска сборщика мусора на регистри должно решится.
Если проблема была в этом, теперь должно писать ошибку в лог, а не молча падать.
Передавай привет команде мегасайта =D
