### ISSUE TITLE
chosen "link" width 4.05 pixels?

### ISSUE THREAD

**Issue by pb6** [Evedel/bow#16]
Hi,

alpine-latest image configured with my local registry (with 1 image pushed) looks like this:
![Screenshot 2020-06-19 at 00 47 12](https://user-images.githubusercontent.com/12859205/85075211-7b63cb00-b1c6-11ea-85ef-96901d74f2ec.png)

I'm using Firefox Nightly, and Developer tools shows this:
![Screenshot 2020-06-19 at 00 49 47](https://user-images.githubusercontent.com/12859205/85075425-d5649080-b1c6-11ea-8bc4-b03119287948.png)

My css-fu is weak, it can't grok 90% vs 4.05px result :)

**Comment by Evedel** [comment]
Hah =) That is weird, thanks for letting me know. I'll have a look at this soon.

**Comment by Evedel** [comment]
Hi, this should be fixed now. Updated docker images are on [docker hub](https://hub.docker.com/repository/docker/evedel/bow).
