### ISSUE TITLE
Daemons error out when they encounter an empty repository

### ISSUE THREAD

**Issue by bstempi** [Evedel/bow#2]
Recently, I had deleted all of the tags out of some given repository that I had set up for a test.  The repository still shows up when calling `/v2/_catalog`.  If you were to call `/v2/REPONAME/tags/list`, you'd get a 404 because there are no tags for this repo.

This 404 causes the checker daemon to stop working.  It'll read the tags in each repo until it gets to the empty one.  In my case, I removed the repository and the checker was able to continue, but the checker shouldn't choke on a 404 like that.  It should be expected that some repos are empty.

**Comment by Evedel** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Daemons error out when they encounter an empty repository](https://trello.com/c/Wbka84fX/56-daemons-error-out-when-they-encounter-an-empty-repository)

**Comment by Evedel** [comment]
@bstempi  Thank you for the report. If you are still interested, I assume, now this problem was fixed.

**Comment by bstempi** [comment]
:+1:  I'll test it when I get a chance.
