### ISSUE TITLE
Wrong permissions when creating /var/lib/bow/

### ISSUE THREAD

**Issue by ebikt** [Evedel/bow#8]
conf/conf.go:29: `os.Mkdir(Env["dbpath"], 0600)` should be `os.Mkdir(Env["dbpath"], 0700)`
When running as non-root user with permissions to create the directory, then bow fails to create the db file in the directory.

**Comment by Evedel** [comment]
Hi, @ebikt!

Thank you for detailed issue report. Will fix it soon.

**Comment by Evedel** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue #8: Wrong permissions when creating /var/lib/bow/](https://trello.com/c/UNlBOh8E/91-issue-8-wrong-permissions-when-creating-var-lib-bow)

**Comment by Evedel** [comment]
@ebikt, there is the updated version on dockerhub at the moment.
