### ISSUE TITLE
repos maxed at 100?

### ISSUE THREAD

**Issue by bibby** [Evedel/bow#9]
Our registry has 500 or more images, and a couple of features seem to fall apart at that scale.

The left-side repo list appears to top out at 100 images. It'd be neat if there was a namespace level instead of one list of everything.

To illustrate, and hoping that formatting works, it'd go from:
```
registry     namespace/app1    {tags}
             namespace/app2
```

to:

```
registry     namespace    app1    {tags}
                          app2
```

Likewise with the *Graph*, it looks to print everything (well, 100) and in no particular order. It'd be great if the left-hand drill-down worked for the graphs view; limiting drawn hierarchies to those include the selected image or tag if one if chosen.

`bow` is looking good. Keep it up!

**Comment by Evedel** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue #9: repos maxed at 100?](https://trello.com/c/Z8wyfrLR/106-issue-9-repos-maxed-at-100)

**Comment by Evedel** [comment]
@bibby 
> bow is looking good. Keep it up!

Thank you, and promise you, I will)

> Our registry has 500 or more images

Indeed, I haven't even try to test it on such a huge scale, so not even surprised that there are some problems.

Unfortunately, right now, I have some deadline in front of me, so I will be able to have a look at any of those issues only after two weeks or so.

Thank you for the detailed issue report.

**Comment by bibby** [comment]
It seems like setting `_catalog?n=` *something high* might do the trick.

https://github.com/Evedel/bow/blob/e24901b2d554fa4f0412d427bb70ac427e026073/project/src/checker/repository.go#L16

**Comment by Evedel** [comment]
I am not sure, need to play around with this.
I definitely don't remember any default limits in api specs https://github.com/docker/distribution/blob/master/docs/spec/api.md#pagination. So, maybe, this is my internal error, maybe, the results indeed need to be iterated through `&last=` parameter

**Comment by Evedel** [comment]
@bibby sooooo, long story short, indeed, the default limit is hardcoded into [distribution](https://github.com/docker/distribution/blob/b6e0cfbdaa1ddc3a17c95142c7bf6e42c5567370/registry/handlers/catalog.go#L16). Now it looks like solved as well as the staff about namespaces filtering. If you are interested in, you can check out the latest build from docker hub.
